(function(){
'use strict';
var COLORS=['red','green','yellow','blue'];
var NAMES={red:'Red',green:'Green',yellow:'Yellow',blue:'Blue'};
var START={red:1,green:14,yellow:27,blue:40};
var FACES=['⚀','⚁','⚂','⚃','⚄','⚅'];
var SAFE=[1,9,14,22,27,35,40,48];
var path=[];
for(var x=0;x<14;x++)path.push([x,0]);
for(var y=1;y<14;y++)path.push([13,y]);
for(var x2=12;x2>=0;x2--)path.push([x2,13]);
for(var y2=12;y2>=1;y2--)path.push([0,y2]);
var lanes={
 red:[[1,6],[2,6],[3,6],[4,6],[5,6],[6,6]],
 green:[[12,6],[11,6],[10,6],[9,6],[8,6],[7,6]],
 yellow:[[12,7],[11,7],[10,7],[9,7],[8,7],[7,7]],
 blue:[[1,7],[2,7],[3,7],[4,7],[5,7],[6,7]]
};
var state={players:4,turn:0,roll:null,rolled:false,busy:false,sound:true,winner:null,tokens:{}};
var board=document.getElementById('ludoBoard');
if(!board)return;
var cells=document.getElementById('boardCells'),layer=document.getElementById('tokensLayer'),rollBtn=document.getElementById('rollDice'),face=document.getElementById('diceFace'),hint=document.getElementById('diceHint'),turnName=document.getElementById('turnName'),turnDot=document.getElementById('turnDot'),turnMessage=document.getElementById('turnMessage'),scoreStack=document.getElementById('scoreStack'),playerCount=document.getElementById('playerCount'),newGame=document.getElementById('newGame'),soundToggle=document.getElementById('soundToggle'),goalFlare=document.getElementById('goalFlare');
function playerColors(){return COLORS.slice(0,state.players)}
function rgba(color,a){var m={red:'255,77,103',green:'41,214,154',yellow:'255,191,63',blue:'77,162,255'};return 'rgba('+m[color]+','+a+')'}
function tone(color){return {red:'#ff4d67',green:'#29d69a',yellow:'#ffbf3f',blue:'#4da2ff'}[color]}
function cellAt(coord,cls){var d=document.createElement('div');d.className=cls;d.style.gridColumn=(coord[0]+1);d.style.gridRow=(coord[1]+1);return d}
function buildBoard(){cells.innerHTML='';path.forEach(function(c,i){var d=cellAt(c,'path-cell'+(SAFE.indexOf(i)>=0?' safe':'')+(i===START.red?' start-red':'')+(i===START.green?' start-green':'')+(i===START.yellow?' start-yellow':'')+(i===START.blue?' start-blue':''));d.dataset.path=i;cells.appendChild(d)});COLORS.forEach(function(color){lanes[color].forEach(function(c,i){var d=cellAt(c,'lane-cell '+color);d.dataset.lane=color+'-'+i;cells.appendChild(d)})});document.querySelectorAll('.home-dots').forEach(function(z){z.innerHTML='<i></i><i></i><i></i><i></i>'})}
function initTokens(){state.tokens={};COLORS.forEach(function(color){state.tokens[color]=[];for(var i=0;i<4;i++)state.tokens[color].push({id:color+'-'+i,color:color,index:i,progress:-1,finished:false})})}
function homeDotPosition(token){var zone=document.querySelector('.home-zone[data-color="'+token.color+'"]');var dots=zone.querySelectorAll('.home-dots i');var r=dots[token.index].getBoundingClientRect(),br=board.getBoundingClientRect();return {x:r.left-br.left+r.width/2,y:r.top-br.top+r.height/2}}
function gridPosition(coord){var br=board.getBoundingClientRect();return {x:(coord[0]+.5)*br.width/14,y:(coord[1]+.5)*br.height/14}}
function tokenPosition(token){if(token.progress<0)return homeDotPosition(token);if(token.progress<=51)return gridPosition(path[(START[token.color]+token.progress)%52]);if(token.progress<=57)return gridPosition(lanes[token.color][token.progress-52]);return gridPosition([6.5,6.5])}
function renderTokens(){layer.innerHTML='';var active=playerColors();active.forEach(function(color){state.tokens[color].forEach(function(token){var b=document.createElement('button');b.type='button';b.className='ludo-token '+color+(token.finished?' finished':'');b.dataset.id=token.id;b.setAttribute('aria-label',NAMES[color]+' token '+(token.index+1));var p=tokenPosition(token);b.style.left=p.x+'px';b.style.top=p.y+'px';if(canMove(token,state.roll)&&state.rolled&&!state.busy)b.classList.add('movable');b.addEventListener('click',function(){if(b.classList.contains('movable'))moveToken(token)});layer.appendChild(b)})});spreadStacked()}
function spreadStacked(){var buckets={};layer.querySelectorAll('.ludo-token').forEach(function(el){var key=Math.round(parseFloat(el.style.left))+'-'+Math.round(parseFloat(el.style.top));(buckets[key]||(buckets[key]=[])).push(el)});Object.keys(buckets).forEach(function(k){var arr=buckets[k];if(arr.length<2)return;arr.forEach(function(el,i){var angle=Math.PI*2*i/arr.length;el.style.marginLeft=(Math.cos(angle)*9)+'px';el.style.marginTop=(Math.sin(angle)*9)+'px'})})}
function canMove(token,roll){if(!roll||token.finished)return false;if(token.progress<0)return roll===6;return token.progress+roll<=57}
function movableTokens(){var c=playerColors()[state.turn];return state.tokens[c].filter(function(t){return canMove(t,state.roll)})}
function currentColor(){return playerColors()[state.turn]}
function setTurnMessage(text){turnMessage.textContent=text}
function updatePanel(){var c=currentColor();turnName.textContent=NAMES[c];turnDot.style.background=tone(c);turnDot.style.boxShadow='0 0 0 7px '+rgba(c,.09)+',0 0 20px '+rgba(c,.3);scoreStack.innerHTML='';playerColors().forEach(function(color,i){var row=document.createElement('div');row.className='player-score'+(i===state.turn?' active':'');var dot=document.createElement('i');dot.style.background=tone(color);var b=document.createElement('b');b.textContent=NAMES[color];var s=document.createElement('span');var fin=state.tokens[color].filter(function(t){return t.finished}).length;s.textContent=fin+'/4 home';row.append(dot,b,s);scoreStack.appendChild(row)});renderTokens()}
function nextTurn(extra){if(state.winner)return;state.roll=null;state.rolled=false;face.textContent='⚀';hint.textContent='Tap to roll';if(!extra)state.turn=(state.turn+1)%state.players;setTurnMessage(extra?'Bonus turn — roll again.':'Roll the dice.');updatePanel()}
function beep(freq,duration){if(!state.sound)return;try{var A=window.AudioContext||window.webkitAudioContext;beep.ctx=beep.ctx||new A();var o=beep.ctx.createOscillator(),g=beep.ctx.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.035,beep.ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,beep.ctx.currentTime+duration);o.connect(g);g.connect(beep.ctx.destination);o.start();o.stop(beep.ctx.currentTime+duration)}catch(e){}}
function rollDice(){if(state.busy||state.rolled||state.winner)return;state.busy=true;rollBtn.classList.add('rolling');var count=0;var timer=setInterval(function(){face.textContent=FACES[Math.floor(Math.random()*6)];count++;if(count>6){clearInterval(timer);state.roll=1+Math.floor(Math.random()*6);face.textContent=FACES[state.roll-1];state.rolled=true;state.busy=false;rollBtn.classList.remove('rolling');hint.textContent='Rolled '+state.roll;beep(300+state.roll*50,.12);var moves=movableTokens();if(!moves.length){setTurnMessage('No legal move.');updatePanel();setTimeout(function(){nextTurn(state.roll===6)},650);return}setTurnMessage(moves.length===1?'Choose the glowing token.':'Choose a glowing token.');updatePanel()}},65)}
function moveToken(token){if(state.busy||!state.rolled||!canMove(token,state.roll))return;state.busy=true;var roll=state.roll;var from=token.progress;token.progress=from<0?0:from+roll;var el=layer.querySelector('[data-id="'+token.id+'"]');if(el)el.classList.add('moving');renderTokens();beep(480,.08);setTimeout(function(){var captured=false,finished=false;if(token.progress<=51){var ring=(START[token.color]+token.progress)%52;if(SAFE.indexOf(ring)<0){playerColors().forEach(function(color){if(color===token.color)return;state.tokens[color].forEach(function(other){if(other.progress>=0&&other.progress<=51&&((START[other.color]+other.progress)%52)===ring){other.progress=-1;other.finished=false;captured=true}})})}}if(token.progress===57&&!token.finished){token.finished=true;finished=true;goalFlare.classList.remove('go');void goalFlare.offsetWidth;goalFlare.classList.add('go');beep(760,.2)}if(captured)beep(220,.18);var allHome=state.tokens[token.color].every(function(t){return t.finished});if(allHome){state.winner=token.color;setTurnMessage(NAMES[token.color]+' wins the game!');turnName.textContent=NAMES[token.color]+' Wins';hint.textContent='New Game to play again';state.busy=false;updatePanel();celebrate(token.color);return}state.busy=false;updatePanel();var extra=roll===6||captured||finished;nextTurn(extra)},380)}
function celebrate(color){for(var i=0;i<34;i++){var p=document.createElement('i');p.style.position='absolute';p.style.zIndex='50';p.style.left='50%';p.style.top='50%';p.style.width='7px';p.style.height='7px';p.style.borderRadius='2px';p.style.background=i%2?tone(color):'#fff';p.style.pointerEvents='none';board.appendChild(p);var a=Math.random()*Math.PI*2,d=90+Math.random()*260,dx=Math.cos(a)*d,dy=Math.sin(a)*d;p.animate([{transform:'translate(-50%,-50%) scale(1)',opacity:1},{transform:'translate('+dx+'px,'+dy+'px) rotate('+(Math.random()*720)+'deg) scale(.2)',opacity:0}],{duration:900+Math.random()*700,easing:'cubic-bezier(.1,.7,.2,1)'}).onfinish=function(){this.effect.target.remove()}}}
function reset(){state.players=parseInt(playerCount.value,10)||4;state.turn=0;state.roll=null;state.rolled=false;state.busy=false;state.winner=null;initTokens();face.textContent='⚀';hint.textContent='Tap to roll';setTurnMessage('Roll the dice to start.');updatePanel()}
rollBtn.addEventListener('click',rollDice);newGame.addEventListener('click',reset);playerCount.addEventListener('change',reset);soundToggle.addEventListener('click',function(){state.sound=!state.sound;soundToggle.textContent=state.sound?'Sound On':'Sound Off';soundToggle.setAttribute('aria-pressed',String(state.sound))});window.addEventListener('resize',function(){renderTokens()},{passive:true});
buildBoard();reset();
})();
