/* Match Center v3 — broad live feeds + premium detail intelligence */
(function(){
'use strict';
var root=document.getElementById('rkSportsPage');if(!root)return;
var grid=root.querySelector('.sw-grid'),feature=root.querySelector('.sw-feature'),tabs=root.querySelector('.sw-tabs'),updated=root.querySelector('.sw-updated'),count=root.querySelector('.sw-count'),refreshBtn=root.querySelector('.sw-refresh'),empty=root.querySelector('.sw-empty'),moreWrap=root.querySelector('.sw-more'),moreBtn=moreWrap&&moreWrap.querySelector('button'),liveCountEl=root.querySelector('.sw-live-count');
var drawer=document.getElementById('matchDrawer'),drawerContent=document.getElementById('matchDrawerContent'),drawerLeague=document.getElementById('drawerLeague'),drawerSport=document.getElementById('drawerSport'),drawerLeagueLogo=document.getElementById('drawerLeagueLogo');
var activeFilter='All',allEvents=[],renderLimit=24,previousScores=new Map(),networkTimer=0,clockTimer=0,firstLoad=true,currentDrawerEvent=null;
var ESPN=[['Football','Premier League','eng.1'],['Football','LaLiga','esp.1'],['Football','Bundesliga','ger.1'],['Football','Serie A','ita.1'],['Football','Ligue 1','fra.1'],['Football','Champions League','uefa.champions'],['Football','Europa League','uefa.europa'],['Football','Conference League','uefa.europa.conf'],['Football','MLS','usa.1'],['Basketball','NBA','basketball/nba'],['Basketball','WNBA','basketball/wnba'],['American Football','NFL','football/nfl'],['Baseball','MLB','baseball/mlb'],['Ice Hockey','NHL','hockey/nhl']];
var TDB_SPORTS=['Soccer','Basketball','Cricket','Tennis','Motorsport','Baseball','Ice Hockey','American Football','Rugby','Volleyball','Handball','Golf'];
var ICONS={Football:'⚽',Soccer:'⚽',Basketball:'🏀',Cricket:'🏏',Tennis:'🎾',Motorsport:'🏎️',Baseball:'⚾','Ice Hockey':'🏒','American Football':'🏈',Rugby:'🏉',Volleyball:'🏐',Handball:'🤾',Golf:'⛳'};
function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
function pad(n){return String(n).padStart(2,'0')}
function localDateKey(){var d=new Date();return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())}
function localESPNDate(){var d=new Date();return d.getFullYear()+pad(d.getMonth()+1)+pad(d.getDate())}
function safeNum(v){if(v===null||v===undefined||v==='')return null;var n=Number(v);return Number.isFinite(n)?n:null}
function initials(name){return String(name||'?').split(/\s+/).filter(Boolean).slice(0,2).map(function(x){return x[0]}).join('').toUpperCase()||'?'}
function sportName(s){return s==='Soccer'?'Football':(s||'Other')}
function iconFor(s){return ICONS[s]||ICONS[sportName(s)]||'●'}
function stateRank(s){return s==='live'?0:s==='upcoming'?1:2}
function fmtTime(ms){if(!ms)return'TBA';try{return new Intl.DateTimeFormat(undefined,{hour:'numeric',minute:'2-digit'}).format(new Date(ms))}catch(e){return new Date(ms).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}}
function fmtDate(ms){if(!ms)return'';var d=new Date(ms),now=new Date();if(d.toDateString()===now.toDateString())return'Today';var t=new Date(now);t.setDate(now.getDate()+1);if(d.toDateString()===t.toDateString())return'Tomorrow';return d.toLocaleDateString(undefined,{month:'short',day:'numeric'})}
function espnBase(code){return code.indexOf('/')>-1?'https://site.api.espn.com/apis/site/v2/sports/'+code:'https://site.api.espn.com/apis/site/v2/sports/soccer/'+code}
function leagueLogoFrom(payload){var l=payload&&payload.leagues&&payload.leagues[0];return l&&l.logos&&l.logos[0]&&l.logos[0].href||''}
function normalizeESPN(payload,meta){var out=[],leagueLogo=leagueLogoFrom(payload);((payload&&payload.events)||[]).forEach(function(ev){var comp=ev.competitions&&ev.competitions[0]||{},comps=comp.competitors||[],home=comps.find(function(c){return c.homeAway==='home'})||comps[0]||{},away=comps.find(function(c){return c.homeAway==='away'})||comps[1]||{},status=comp.status||ev.status||{},type=status.type||{},state=type.state==='in'?'live':type.state==='post'?'done':'upcoming',start=Date.parse(ev.date||comp.date||'')||0,venue=comp.venue||{},address=venue.address||{},league=(ev.league&&ev.league.name)||(payload.leagues&&payload.leagues[0]&&payload.leagues[0].name)||meta[1]||'';function side(c){var tm=c.team||{},score=state==='upcoming'?null:safeNum(c.score);return{name:tm.displayName||c.displayName||'Team',short:tm.shortDisplayName||'',logo:tm.logo||'',score:score,record:c.records&&c.records[0]&&c.records[0].summary||''}}
 out.push({id:'espn-'+ev.id,providerId:String(ev.id||''),sport:meta[0],league:league,leagueLogo:leagueLogo,leagueCode:meta[2],country:address.country||'',venue:venue.fullName||'',venueCity:address.city||'',venueState:address.state||'',start:start,state:state,statusText:type.shortDetail||type.detail||'',clock:status.displayClock||'',period:status.period||null,home:side(home),away:side(away),source:'ESPN',summaryUrl:espnBase(meta[2])+'/summary?event='+encodeURIComponent(ev.id)});
 });return out}
function parseTDBStart(e){if(e.strTimestamp){var n=Date.parse(e.strTimestamp);if(!isNaN(n))return n}var t=Date.parse((e.dateEvent||localDateKey())+'T'+(e.strTime||'00:00:00'));return isNaN(t)?0:t}
function normalizeTDB(payload,sport){return((payload&&payload.events)||[]).map(function(e){var start=parseTDBStart(e),hs=safeNum(e.intHomeScore),as=safeNum(e.intAwayScore),now=Date.now(),lower=String(e.strStatus||e.strProgress||'').toLowerCase(),state=/live|in progress|1h|2h|half|quarter|period|inning|set/.test(lower)?'live':/finished|ft|final|ended|aet|after/.test(lower)?'done':'upcoming';if(state==='upcoming'&&(hs!==null||as!==null)&&start&&now>=start&&now-start<5*3600000)state='live';if(state==='upcoming'&&start&&now>start+7*3600000)state='done';if(state==='upcoming'){hs=null;as=null}return{id:'tdb-'+(e.idEvent||[sport,e.strEvent,start].join('-')),providerId:e.idEvent||'',sport:sportName(e.strSport||sport),league:e.strLeague||'',leagueLogo:e.strLeagueBadge||e.strLeagueLogo||'',leagueCode:'',country:e.strCountry||'',venue:e.strVenue||'',venueCity:e.strCity||'',venueState:'',start:start,state:state,statusText:e.strStatus||e.strProgress||'',clock:e.strProgress||'',period:null,home:{name:e.strHomeTeam||'',short:'',logo:e.strHomeTeamBadge||'',score:hs,record:''},away:{name:e.strAwayTeam||'',short:'',logo:e.strAwayTeamBadge||'',score:as,record:''},eventName:e.strEvent||'',source:'TheSportsDB'} })}
function fetchJSON(url,timeout){var c=new AbortController(),timer=setTimeout(function(){c.abort()},timeout||7000);return fetch(url,{cache:'no-store',mode:'cors',signal:c.signal}).then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}).finally(function(){clearTimeout(timer)})}
function fetchESPN(){var date=localESPNDate();return Promise.allSettled(ESPN.map(function(meta){return fetchJSON(espnBase(meta[2])+'/scoreboard?dates='+date+'&limit=100',7000).then(function(j){return normalizeESPN(j,meta)})})).then(function(rs){var out=[];rs.forEach(function(r){if(r.status==='fulfilled')out=out.concat(r.value)});return out})}
function fetchTDB(){var date=localDateKey();return Promise.allSettled(TDB_SPORTS.map(function(s){return fetchJSON('https://www.thesportsdb.com/api/v1/json/123/eventsday.php?d='+encodeURIComponent(date)+'&s='+encodeURIComponent(s),7500).then(function(j){return normalizeTDB(j,s)})})).then(function(rs){var out=[];rs.forEach(function(r){if(r.status==='fulfilled')out=out.concat(r.value)});return out})}
function dedupe(events){var seen=new Map();events.forEach(function(e){var key=[sportName(e.sport),String(e.home&&e.home.name||'').toLowerCase(),String(e.away&&e.away.name||'').toLowerCase(),Math.round((e.start||0)/600000)].join('|'),old=seen.get(key);if(!old||e.source==='ESPN'||(!old.home.logo&&e.home.logo))seen.set(key,e)});return Array.from(seen.values())}
function sortEvents(a){return a.sort(function(x,y){var sr=stateRank(x.state)-stateRank(y.state);if(sr)return sr;return(x.start||0)-(y.start||0)})}
function filtered(){return activeFilter==='All'?allEvents:allEvents.filter(function(e){return sportName(e.sport)===activeFilter})}
function logoHTML(url,name){return url?'<img src="'+esc(url)+'" alt="" loading="lazy" decoding="async" referrerpolicy="no-referrer" onerror="this.parentNode.innerHTML=\'<span class=&quot;sw-logo-fallback&quot;>'+esc(initials(name))+'</span>\'">':'<span class="sw-logo-fallback">'+esc(initials(name))+'</span>'}
function leagueLogoHTML(e,mini){var c=mini?'sw-mini-league-logo':'sw-league-logo';return'<span class="'+c+'">'+(e.leagueLogo?'<img src="'+esc(e.leagueLogo)+'" alt="" loading="lazy" referrerpolicy="no-referrer">':'<span class="sw-logo-fallback">'+esc(initials(e.league))+'</span>')+'</span>'}
function stateText(e,dot){if(e.state==='live')return(dot?'<i class="sw-live-dot"></i>':'')+(e.clock||e.statusText||'LIVE');if(e.state==='done')return e.statusText||'FINAL';return fmtDate(e.start)+' · '+fmtTime(e.start)}
function clockText(e){if(e.state!=='live')return stateText(e,false);if(e.clock)return e.clock;if(!e.start)return'LIVE';var sec=Math.max(0,Math.floor((Date.now()-e.start)/1000));return Math.floor(sec/60)+':'+pad(sec%60)}
function scoreText(v,e){return e.state==='upcoming'?'—':(v===null?'—':String(v))}
function teamRow(t,e){return'<div class="sw-team-row"><span class="sw-team-logo">'+logoHTML(t.logo,t.name)+'</span><span class="sw-team-name"><b title="'+esc(t.name)+'">'+esc(t.name||'Team')+'</b><small>'+esc(t.record||e.country||'')+'</small></span><strong class="sw-team-score '+(e.state==='upcoming'?'pending':'')+'">'+esc(scoreText(t.score,e))+'</strong></div>'}
function cardHTML(e){var hasTeams=e.home&&e.away&&(e.home.name||e.away.name);if(!hasTeams)return'<article class="sw-card" data-event="'+esc(e.id)+'"><div class="sw-card-top"><span class="sw-card-sport">'+iconFor(e.sport)+' '+esc(sportName(e.sport))+'</span><span class="sw-card-state">'+stateText(e,true)+'</span></div><div class="sw-event-only"><b>'+esc(e.eventName||e.league||sportName(e.sport))+'</b></div></article>';return'<article class="sw-card '+(e.state==='live'?'live':'')+'" data-event="'+esc(e.id)+'" tabindex="0" role="button"><div class="sw-card-top"><span class="sw-card-sport">'+iconFor(e.sport)+' '+esc(sportName(e.sport))+'</span><span class="sw-card-state">'+stateText(e,true)+'</span></div><div class="sw-league-line">'+leagueLogoHTML(e,true)+'<p class="sw-league">'+esc(e.league||e.country||'Worldwide')+'</p></div><div class="sw-teams">'+teamRow(e.home,e)+teamRow(e.away,e)+'</div><div class="sw-card-foot"><span class="sw-card-clock" data-clock="'+esc(e.id)+'">'+esc(clockText(e))+'</span><span class="sw-country">'+esc(e.venue||e.country||e.source)+'</span><span class="sw-open-hint">Details ↗</span></div></article>'}
function featureTeam(t,e){return'<div class="sw-feature-team"><span class="sw-feature-logo">'+logoHTML(t.logo,t.name)+'</span><h3>'+esc(t.name||'Event')+'</h3><small>'+esc(t.record||e.country||'')+'</small></div>'}
function featureHTML(e){if(!feature)return;if(!e){feature.hidden=true;return}feature.hidden=false;feature.className='sw-feature '+(e.state==='live'?'live':'');feature.dataset.event=e.id;var scores=e.state==='upcoming'?'<div class="sw-scoreline"><span>VS</span></div>':'<div class="sw-scoreline"><span>'+esc(scoreText(e.home.score,e))+'</span><i></i><span>'+esc(scoreText(e.away.score,e))+'</span></div>';feature.innerHTML='<div class="sw-feature-head"><div class="sw-feature-league">'+leagueLogoHTML(e,false)+'<b>'+esc(e.league||sportName(e.sport))+'</b></div><div class="sw-feature-status '+(e.state==='live'?'live':e.state==='done'?'post':'pre')+'">'+stateText(e,true)+'</div></div>'+featureTeam(e.home,e)+'<div class="sw-feature-score">'+scores+'<span class="sw-clock" data-feature-clock="'+esc(e.id)+'">'+esc(clockText(e))+'</span><span class="sw-feature-note">'+esc(e.venue||e.country||e.source)+'</span></div>'+featureTeam(e.away,e)}
function renderTabs(){var sports=['All'].concat(Array.from(new Set(allEvents.map(function(e){return sportName(e.sport)}))).sort());tabs.innerHTML=sports.map(function(s){return'<button class="sw-tab '+(activeFilter===s?'active':'')+'" type="button" data-sport="'+esc(s)+'"><span class="emoji">'+(s==='All'?'✦':iconFor(s))+'</span>'+esc(s==='All'?'All Sports':s)+'</button>'}).join('')}
function render(){var arr=filtered(),featured=arr.find(function(e){return e.state==='live'})||arr[0]||null;featureHTML(featured);grid.innerHTML=arr.slice(featured?1:0,renderLimit+(featured?1:0)).map(cardHTML).join('');empty.hidden=!!arr.length;moreWrap.hidden=arr.length<=renderLimit;count.innerHTML='<strong>'+allEvents.length+'</strong> events';var lc=allEvents.filter(function(e){return e.state==='live'}).length;liveCountEl.innerHTML='<b class="sw-live-dot"></b><strong>'+lc+'</strong> live';bindCards()}
function bindCards(){grid.querySelectorAll('.sw-card[data-event]').forEach(function(c){function go(){var e=allEvents.find(function(x){return x.id===c.dataset.event});if(e)openDrawer(e)}c.addEventListener('click',go);c.addEventListener('keydown',function(ev){if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();go()}})});if(feature){feature.onclick=function(){var e=allEvents.find(function(x){return x.id===feature.dataset.event});if(e)openDrawer(e)}}}
function updateClocks(){document.querySelectorAll('[data-clock],[data-feature-clock]').forEach(function(el){var id=el.getAttribute('data-clock')||el.getAttribute('data-feature-clock'),e=allEvents.find(function(x){return x.id===id});if(e)el.textContent=clockText(e)})}
function detectGoals(next){if(firstLoad){next.forEach(function(e){previousScores.set(e.id,[e.home&&e.home.score,e.away&&e.away.score])});firstLoad=false;return}next.forEach(function(e){if(e.sport!=='Football'||e.state!=='live'||!e.home||!e.away)return;var prev=previousScores.get(e.id),cur=[e.home.score,e.away.score],ph=prev?safeNum(prev[0]):null,pa=prev?safeNum(prev[1]):null;if(prev&&cur[0]!==null&&cur[1]!==null&&((ph!==null&&cur[0]>ph)||(pa!==null&&cur[1]>pa)))showGoal(e,ph!==null&&cur[0]>ph?e.home.name:e.away.name,cur);previousScores.set(e.id,cur)})}
function showGoal(e,team,score){var g=document.querySelector('.sw-goal');if(!g)return;g.querySelector('b').textContent=team;g.querySelector('span').textContent=score[0]+'–'+score[1];g.classList.remove('on');void g.offsetWidth;g.classList.add('on');setTimeout(function(){g.classList.remove('on')},2100)}
function refresh(){if(refreshBtn)refreshBtn.classList.add('loading');Promise.allSettled([fetchESPN(),fetchTDB()]).then(function(rs){var merged=[];rs.forEach(function(r){if(r.status==='fulfilled')merged=merged.concat(r.value)});if(!merged.length)throw new Error('No feeds');merged=sortEvents(dedupe(merged));detectGoals(merged);allEvents=merged;renderTabs();render();updated.textContent='Updated '+fmtTime(Date.now());schedule()}).catch(function(){updated.textContent='Reconnecting…';schedule(20000)}).finally(function(){if(refreshBtn)refreshBtn.classList.remove('loading')})}
function schedule(delay){clearTimeout(networkTimer);var live=allEvents.some(function(e){return e.state==='live'});networkTimer=setTimeout(refresh,delay||(live?8000:30000))}
tabs.addEventListener('click',function(e){var b=e.target.closest('.sw-tab');if(!b)return;activeFilter=b.dataset.sport||'All';renderLimit=24;renderTabs();render()});if(refreshBtn)refreshBtn.addEventListener('click',function(){clearTimeout(networkTimer);refresh()});if(moreBtn)moreBtn.addEventListener('click',function(){renderLimit+=24;render()});clockTimer=setInterval(updateClocks,1000);
function weatherIcon(code){if(code===0)return'☀️';if(code<=3)return'🌤️';if(code<=48)return'🌫️';if(code<=67)return'🌧️';if(code<=77)return'🌨️';if(code<=82)return'🌦️';if(code<=99)return'⛈️';return'🌡️'}
function getWeather(e){var q=e.venueCity||e.venue||'';if(!q)return Promise.resolve(null);return fetchJSON('https://geocoding-api.open-meteo.com/v1/search?name='+encodeURIComponent(q)+'&count=1&language=en&format=json',6500).then(function(g){var p=g&&g.results&&g.results[0];if(!p)return null;return fetchJSON('https://api.open-meteo.com/v1/forecast?latitude='+p.latitude+'&longitude='+p.longitude+'&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m&timezone=auto',6500).then(function(w){var c=w&&w.current;if(!c)return null;return{place:p.name+(p.country?', '+p.country:''),temp:c.temperature_2m,feels:c.apparent_temperature,wind:c.wind_speed_10m,code:c.weather_code}})}).catch(function(){return null})}
function getSummary(e){return e.summaryUrl?fetchJSON(e.summaryUrl,8000).catch(function(){return null}):Promise.resolve(null)}
function rosterFrom(summary){var rs=summary&&summary.rosters;if(!Array.isArray(rs))return[];return rs.map(function(team){var roster=team.roster||team.athletes||[],starters=roster.filter(function(x){return x.starter===true||x.starter==='true'}).slice(0,11);if(!starters.length&&roster.length>=11)starters=roster.slice(0,11);return{team:team.team&&team.team.displayName||team.displayName||'',formation:team.formation||'',players:starters.map(function(x,i){var a=x.athlete||x;return{name:a.displayName||a.fullName||a.shortName||'Player',jersey:a.jersey||a.uniform||String(i+1),position:x.position&&x.position.abbreviation||a.position&&a.position.abbreviation||''}})}})}
function probabilities(summary){var p=summary&&summary.predictor;if(p){var h=safeNum(p.homeTeam&&p.homeTeam.gameProjection),a=safeNum(p.awayTeam&&p.awayTeam.gameProjection);if(h!==null&&a!==null){var draw=Math.max(0,100-h-a);return{home:h,draw:draw,away:a,label:'ESPN predictor'}}}var pc=summary&&summary.pickcenter&&summary.pickcenter[0];if(pc){var ho=safeNum(pc.homeTeamOdds&&pc.homeTeamOdds.winPercentage),ao=safeNum(pc.awayTeamOdds&&pc.awayTeamOdds.winPercentage),dr=safeNum(pc.drawOdds&&pc.drawOdds.winPercentage);if(ho!==null&&ao!==null)return{home:ho,draw:dr===null?Math.max(0,100-ho-ao):dr,away:ao,label:'ESPN odds model'}}return null}
function drawerLogo(e){drawerLeagueLogo.innerHTML=e.leagueLogo?'<img src="'+esc(e.leagueLogo)+'" alt="">':'<span class="sw-logo-fallback">'+esc(initials(e.league))+'</span>'}
function openDrawer(e){currentDrawerEvent=e;drawer.hidden=false;drawer.setAttribute('aria-hidden','false');drawerSport.textContent=sportName(e.sport).toUpperCase()+' · '+(e.state==='live'?'LIVE':'MATCH');drawerLeague.textContent=e.league||sportName(e.sport);drawerLogo(e);drawerContent.innerHTML='<div class="match-loading"><i></i><span>Loading match intelligence…</span></div>';requestAnimationFrame(function(){drawer.classList.add('open')});document.body.style.overflow='hidden';Promise.all([getSummary(e),getWeather(e)]).then(function(r){if(currentDrawerEvent&&currentDrawerEvent.id===e.id)renderDrawer(e,r[0],r[1])})}
function closeDrawer(){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');document.body.style.overflow='';setTimeout(function(){drawer.hidden=true},260);currentDrawerEvent=null}
document.querySelectorAll('[data-close-match]').forEach(function(b){b.addEventListener('click',closeDrawer)});window.addEventListener('keydown',function(e){if(e.key==='Escape'&&drawer&&!drawer.hidden)closeDrawer()});
function probabilityHTML(p,e){if(!p)return'<div class="md-card md-prob"><div class="md-card-label">WIN PROBABILITY</div><p class="md-unavailable">No trusted pre-match probability is available from the connected provider for this fixture.</p></div>';function row(n,v){return'<div class="md-prob-row"><b>'+esc(n)+'</b><div class="md-prob-track"><div class="md-prob-fill" style="width:'+Math.max(0,Math.min(100,v))+'%"></div></div><span>'+Math.round(v)+'%</span></div>'}return'<div class="md-card md-prob"><div class="md-card-label">WIN PROBABILITY</div>'+row(e.home.short||e.home.name,p.home)+(p.draw!==null&&p.draw!==undefined?row('Draw',p.draw):'')+row(e.away.short||e.away.name,p.away)+'<div class="md-prob-note">Source: '+esc(p.label)+' · probabilities can change as provider data updates.</div></div>'}
function lineupsHTML(rs,e){if(!rs.length)return'<div class="md-lineups"><div class="md-lineups-head"><strong>Expected / Starting XI</strong><span>Provider data</span></div><div class="md-unavailable">Lineups are not published yet for this match. They will appear here when the connected match provider publishes them.</div></div>';var cols=rs.slice(0,2).map(function(t,i){return'<div class="md-lineup-team"><h4>'+esc(t.team||(i===0?e.home.name:e.away.name))+(t.formation?' · '+esc(t.formation):'')+'</h4>'+t.players.map(function(p){return'<div class="md-player"><i>'+esc(p.jersey||'')+'</i><span>'+esc(p.name)+(p.position?' · '+esc(p.position):'')+'</span></div>'}).join('')+'</div>'}).join('');return'<div class="md-lineups"><div class="md-lineups-head"><strong>Expected / Starting XI</strong><span>Published provider lineup</span></div><div class="md-lineup-cols">'+cols+'</div></div>'}
function renderDrawer(e,summary,weather){var p=probabilities(summary),rs=rosterFrom(summary),score=e.state==='upcoming'?'<span>VS</span>':'<span>'+esc(scoreText(e.home.score,e))+'</span><em>–</em><span>'+esc(scoreText(e.away.score,e))+'</span>';var weatherHTML=weather?'<div class="md-card"><div class="md-card-label">VENUE WEATHER</div><div class="md-weather-main"><span class="md-weather-icon">'+weatherIcon(weather.code)+'</span><div><strong>'+Math.round(weather.temp)+'°</strong><p>Feels '+Math.round(weather.feels)+'° · Wind '+Math.round(weather.wind)+' km/h</p></div></div><p>'+esc(weather.place)+'</p></div>':'<div class="md-card"><div class="md-card-label">VENUE WEATHER</div><strong>Not available</strong><p>Venue location could not be resolved reliably.</p></div>';drawerContent.innerHTML='<div class="md-scoreboard"><div class="md-status">'+stateText(e,false)+'</div><div class="md-score-row"><div class="md-team"><span class="md-team-logo">'+logoHTML(e.home.logo,e.home.name)+'</span><b>'+esc(e.home.name)+'</b></div><div class="md-score">'+score+'</div><div class="md-team"><span class="md-team-logo">'+logoHTML(e.away.logo,e.away.name)+'</span><b>'+esc(e.away.name)+'</b></div></div></div><div class="md-info-grid"><div class="md-card"><div class="md-card-label">VENUE</div><strong>'+esc(e.venue||'Venue TBA')+'</strong><p>'+esc([e.venueCity,e.venueState,e.country].filter(Boolean).join(', ')||'Location not published')+'</p></div>'+weatherHTML+probabilityHTML(p,e)+'</div>'+lineupsHTML(rs,e)}
refresh();
})();
